name: E2E Tests

on:
  pull_request:
    branches:
      - master

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Ping scorewiz
        run: curl -s https://scorewiz.eu

      - name: Get firefox version
        run: firefox --version

      - name: Setup Firefox Driver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz
          sudo tar -xvf geckodriver-*.tar.gz      
          sudo mv geckodriver /usr/local/share/gecko_driver/

      - name: Check Firefox Driver installation
        run: geckodriver --version

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          ./gradlew test -i --no-parallel
        env:
          SW_USERNAME: ${{ secrets.SCOREWIZ_USERNAME }}
          SW_PASSWORD: ${{ secrets.SCOREWIZ_PASSWORD }}
          SW_BASE_URL: https://scorewiz.eu
          SW_SCOREBOARD_NAME: CI-TEST
          GOOGLE_CREDS_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_CREDS_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GS_VOTE_ID: ${{ secrets.GOOGLE_SPREADSHEET_VOTE_ID }}
          GS_TELEVOTE_ID: ${{ secrets.GOOGLE_SPREADSHEET_TELEVOTE_ID }}
          GS_PARTICIPANTS_ID: ${{ secrets.GOOGLE_SPREADSHEET_PARTICIPANTS_ID }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "Test Results"
          path: build

#      - uses: actions/upload-artifact@v2
#        with:
#          name: "Compiled artifacts for Pull Request #${{github.event.number}}"
#          path: build/libs
